### ISSUE TITLE
Code Review for the app

### ISSUE THREAD

**Issue by winkerVSbecks** [rangle/react-native-workshop#10]

**Comment by sachasayan** [comment]
Text input is kinda janky on Android. Should we fix this?

<img width="393" alt="screen shot 2016-05-16 at 4 29 03 pm" src="https://cloud.githubusercontent.com/assets/1666034/15302979/9e7ff54c-1b83-11e6-8662-0a9635fe880d.png">

**Comment by winkerVSbecks** [comment]
Yes. Actually that's a good point. I haven't tested this on Android. Would you be interested in doing that and creating cards for all the bugs?

**Comment by sachasayan** [comment]
I'll see what I can do. Might take me a bit, as this entirely new territory for me. 💩 

So far, this is the only true bug that stands out. I'm going to do a more thorough comparison between the two versions right now, though.

**Comment by winkerVSbecks** [comment]
Just logging the bugs for now should be fine. The main priority is to finish the gitbook content.
