### ISSUE TITLE
Search / input broken on Android builds.

### ISSUE THREAD

**Issue by sachasayan** [rangle/react-native-workshop#16]
Keyboard / text input visually broken on Android builds. It seems to work functionally — just not visually. Not sure what's happening here, but the iOS version looks much more graceful: 

<img width="765" alt="screen shot 2016-05-16 at 4 51 42 pm" src="https://cloud.githubusercontent.com/assets/1666034/15303695/0b73c77a-1b87-11e6-8b47-8c93b594b441.png">

**Comment by winkerVSbecks** [comment]
This might be because of the keyboard spacer. I guess Android doesn't need it.
