### ISSUE TITLE
Spacing inconsistencies between Android and iOS builds.

### ISSUE THREAD

**Issue by sachasayan** [rangle/react-native-workshop#17]
We should take a look at these. 

(1)
<img width="763" alt="screen shot 2016-05-16 at 4 50 50 pm" src="https://cloud.githubusercontent.com/assets/1666034/15303747/60a7ccd2-1b87-11e6-917e-1cf9d4afd0e7.png">

(2)
<img width="794" alt="screen shot 2016-05-16 at 4 52 16 pm" src="https://cloud.githubusercontent.com/assets/1666034/15303748/60ac4aa0-1b87-11e6-8cb8-402fd15c0d93.png">

**Comment by winkerVSbecks** [comment]
The navigation bar is expected – it's left aligned on Android. I'll look into the others.
