### ISSUE TITLE
Create base branch for workshop and overview chapter on what it includes

### ISSUE THREAD

**Issue by sachasayan** [rangle/react-native-workshop#18]

**Comment by sachasayan** [comment]
Following discussion with @riavalon and pending confirmation with @winkerVSbecks 

While we have a final build for what our app is going to look like, we don't have a 'starter' branch for workshop participants, to begin from, and we haven't defined what exactly should be pre-defined in that branch.

**Comment by winkerVSbecks** [comment]
👍 we can create the base branches once we have the content.

**Comment by sachasayan** [comment]
@winkerVSbecks Counterpoint: We don't know what to cover in the workshop on the granular level if we don't have the base branch well-defined.

**Comment by winkerVSbecks** [comment]
Branches:
- [x] hello-world
- [x] base branch with redux, api, etc setup
- [x] navigator solution
- [x] Pokedex solution
- [x] Search solution
- [x] Loader solution
- [x] PokemonDetails solution (master)
