### ISSUE TITLE
Break down ListView section

### ISSUE THREAD

**Issue by winkerVSbecks** [rangle/react-native-workshop#48]
Add a short intro to ListView and then break down the section into 4 tasks:
- ListView
- SearchBar (with an intro for `textInput`)
- KeyboardSpacer
- Wire up `goTo`

**Comment by relaxedtomato** [comment]
@winkerVSbecks: Not clear what is meant by `goTo`, the navigation is discussed briefly in the `ListView` portion. Will push a PR, we can review then.
