### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by winkerVSbecks** [rangle/react-native-workshop#8]
- Need to add an example component test with Enzyme. Something similar to this: https://github.com/rangle/react-native-training/blob/07-ui-testing/test/Button.js

**Comment by riavalon** [comment]
There are a lot of dependency issues trying to get testing setup in the project. It requires react-dom, react-native-mock, react-addons-test-utils, and all of these are throwing peer dependency errors. Might take a while getting the test suite ready to run. cc @winkerVSbecks
